config/routes.rb
ThePitch::Application.routes.draw do

  get "pitch_attachment/new", :as => "new_pitch_attachment"
  post "pitch_attachment/create"

  delete '/pitch_attachment/:id' => 'PitchAttachment#destroy', :as => "pitch_attachment_destroy"

  get '/pitch_attachment/:id/edit' => 'PitchAttachment#edit', :as => "pitch_attachment_edit"

  put '/pitch_attachment/:id' => 'PitchAttachment#update', :as => "pitch_attachment_update"
 
  get "attachment/new"

  get "attachment/create"

  delete "attachment/delete"


root :to => 'Sessions#landingpage'

get '/aboutus' => 'sessions#about_us', :as => 'about_us'

get '/employerlogin' => 'sessions#newemployer', :as => 'employerlogin'
post '/sessions/createemployer' => 'sessions#create_employer'
get '/logout' => 'sessions#destroy', :as => 'logout'

get '/userlogin' => 'sessions#newuser', :as => 'userlogin'
post '/sessions/createuser' => 'sessions#create_user', :as => 'createuser'


get '/users', controller: 'Users', action: 'index', :as => 'users'
post '/users', controller: 'Users', action: 'create'
get '/users/new', controller: 'Users', action: 'new', :as => 'new_user'
get '/users/:id/edit', controller: 'Users', action: 'edit', :as => 'edit_user'
get '/users/:id', controller: 'Users', action: 'show', :as => 'user'

put '/users/:id', controller: 'Users', action: 'update'
delete '/users/:id', controller: 'Users', action: 'destroy'


get '/pitches/new' => 'Pitch#new', :as => 'new_pitch'
post '/pitches' => 'Pitch#create'
get '/pitches' => 'Pitch#index', :as => 'pitches'
get '/pitches/:id' => 'Pitch#show', :as => 'pitch'
delete '/pitches/:id' => 'Pitch#destroy'
put '/pitches/:id' => 'Pitch#update'
get '/pitches/:id/edit' => 'Pitch#edit', :as => 'edit_pitch'
post '/shorten/:id' => 'Pitch#shorten', :as => 'shorten'
get '/email/:id' => 'Pitch#email', :as => 'email'
get '/*userid/*pitchid/a-pitch-from/*userfirstname' => 'Pitch#short_url'
get '/a_pitch/*short_descriptive_url' => 'Pitch#short_url'

get '/employers' => 'employers#index', :as => 'employers'
get '/employers/new' => 'employers#new', :as => 'new_employer'
post '/employers' => 'employers#create'
get '/employers/:id' => 'employers#show', :as => 'employer'
get '/employers/:id/edit' => 'employers#edit', :as => 'edit'
put '/employers/:id' => 'employers#update', :as => 'update'
delete '/employers/:id' => 'employers#destroy', :as => 'delete'


get '/jobs' => 'jobs#index', :as => 'jobs'
get '/jobs/new' => 'jobs#new', :as => 'new_job'
post '/jobs' => 'jobs#create'
get '/jobs/:id' => 'jobs#show', :as => 'job'
get '/jobs/:id/edit' => 'jobs#edit', :as => 'edit_job'
put '/jobs/:id' => 'jobs#update', :as => 'update_job'
delete '/jobs/:id' => 'jobs#destroy', :as => 'destroy_job'

get "prompt/new" => 'prompt#new', :as => 'new_prompt'
post "prompt/create" => 'prompt#create'
delete "prompt/:id" => 'prompt#delete', :as => 'prompt'

get "/mockup/home" => 'mockup#home'


end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :description, :title, :employer_id, :maxpitchcount
  
  has_many :pitches
  belongs_to :employer
  
  def employer
    Employer.find_by_id(self.employer_id)
  end
  
 
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  
  before_filter :ensure_logged_in


  def index
    @jobs=Job.all
  end
  
  def new
    @job=Job.new
  end
  
  def create
    @job=Job.new(params[:job])
    @job.employer_id = session[:employer_id]
    @job.save
    redirect_to employer_path(@job.employer_id)
  end
  
  def show
     @job=Job.find_by_id(params[:id])
     @pitches = Pitch.where(:job_id => @job.id)
  end
  
  def edit
     @job=Job.find_by_id(params[:id])
  end
  
  def update
     @job=Job.find_by_id(params[:id])
     @job.update_attributes(params[:job])
     
     redirect_to job_url
  end
  
  def destroy
     @job=Job.find_by_id(params[:id])
     employer = @job.employer_id
     @job.destroy
     
     redirect_to employer_url(employer)
  end
  
end

app/views/jobs/_form.html.erb
<%= form_for @job do |j| %>
  <%= j.label :title%>
  <%= j.text_field :title%>
  
  <%= j.label :description%>
  <%= j.text_field :description%>
  
  <%= j.label :maxpitchcount%>
  <%= j.text_field :maxpitchcount%>
  
<!--   taken out because employer_id should assign via session has -->h
  <%#= j.label :employer_id %>
  <%#= j.collection_select :employer_id, Employer.all, :id, :name %>
  
  <%= j.submit "Create Job!"%>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit this job</h1>

<%= render 'form' %>

app/views/jobs/index.html.erb
<h1> Hate your job? Find a new one below</h1>
<div id='notice'><%=flash[:notice]%></div>
<div class="job_list">
	<table class="table table-hover">
	<% @jobs.each do |job| %>
		<tr>
		<td>	
		 <ul>Title:<%= job.title %>  |
		 <%= link_to "Details", job_url(job.id) %></ul>
		 <ul>Description: <%= job.description %> <ul>
		</td>
		</tr>
		<% end %>
	</table>
</div>

app/views/jobs/new.html.erb
<h1>Create new job</h1>

<%= render 'form'%>

app/views/jobs/show.html.erb
<h1> Job Details </h1>
<%= flash[:notice] %>

<div class="container">
	<div class = "row-fluid span 12">
Title: <%= @job.title%></div>
Description: <%= @job.description%>
Employer Name: <%= @job.employer.name%>
Maximum Pitches Allowed: <%= @job.maxpitchcount%>
Current Pitch Count: <%= @job.pitches.count%>

<br><br>

<% if session[:user_id]==nil && session[:employer_id] != nil %>
	<b>Pitches for this job (A lookbook!):
		<ul>
			<% @pitches.each do |pitch_object| %>
				<li><%= link_to pitch_object.headline, pitch_url(pitch_object.id) %>
				</li>
			<%end%>
		</ul>
	<%= link_to "Edit", edit_job_url%>
	<%= link_to "Destroy ME!", destroy_job_url, :method => 'delete'%>
<% else%>
	<%= form_tag(new_pitch_url, :method => "get") do %>
	<%= hidden_field_tag :job_id, @job.id  %>
	
	  <% if @job.pitches.count >= @job.maxpitchcount %>
	    This job can not currently be pitched.
	  <% else %>
	    <%= submit_tag "Pitch This Job"%>
	  <%end%>
	<%end%>
<%end%>

</div>