config/routes.rb
ThePitch::Application.routes.draw do

  get "pitch_attachment/new", :as => "new_pitch_attachment"
  post "pitch_attachment/create"

  delete '/pitch_attachment/:id' => 'PitchAttachment#destroy', :as => "pitch_attachment_destroy"

  get '/pitch_attachment/:id/edit' => 'PitchAttachment#edit', :as => "pitch_attachment_edit"

  put '/pitch_attachment/:id' => 'PitchAttachment#update', :as => "pitch_attachment_update"
 
  get "attachment/new"

  get "attachment/create"

  delete "attachment/delete"


root :to => 'Sessions#landingpage'

get '/aboutus' => 'sessions#about_us', :as => 'about_us'

get '/employerlogin' => 'sessions#newemployer', :as => 'employerlogin'
post '/sessions/createemployer' => 'sessions#create_employer'
get '/logout' => 'sessions#destroy', :as => 'logout'

get '/userlogin' => 'sessions#newuser', :as => 'userlogin'
post '/sessions/createuser' => 'sessions#create_user', :as => 'createuser'


get '/users', controller: 'Users', action: 'index', :as => 'users'
post '/users', controller: 'Users', action: 'create'
get '/users/new', controller: 'Users', action: 'new', :as => 'new_user'
get '/users/:id/edit', controller: 'Users', action: 'edit', :as => 'edit_user'
get '/users/:id', controller: 'Users', action: 'show', :as => 'user'

put '/users/:id', controller: 'Users', action: 'update'
delete '/users/:id', controller: 'Users', action: 'destroy'


get '/pitches/new' => 'Pitch#new', :as => 'new_pitch'
post '/pitches' => 'Pitch#create'
get '/pitches' => 'Pitch#index', :as => 'pitches'
get '/pitches/:id' => 'Pitch#show', :as => 'pitch'
delete '/pitches/:id' => 'Pitch#destroy'
put '/pitches/:id' => 'Pitch#update'
get '/pitches/:id/edit' => 'Pitch#edit', :as => 'edit_pitch'
post '/shorten/:id' => 'Pitch#shorten', :as => 'shorten'
get '/email/:id' => 'Pitch#email', :as => 'email'
get '/*userid/*pitchid/a-pitch-from/*userfirstname' => 'Pitch#short_url'
get '/a_pitch/*short_descriptive_url' => 'Pitch#short_url'

get '/employers' => 'employers#index', :as => 'employers'
get '/employers/new' => 'employers#new', :as => 'new_employer'
post '/employers' => 'employers#create'
get '/employers/:id' => 'employers#show', :as => 'employer'
get '/employers/:id/edit' => 'employers#edit', :as => 'edit'
put '/employers/:id' => 'employers#update', :as => 'update'
delete '/employers/:id' => 'employers#destroy', :as => 'delete'


get '/jobs' => 'jobs#index', :as => 'jobs'
get '/jobs/new' => 'jobs#new', :as => 'new_job'
post '/jobs' => 'jobs#create'
get '/jobs/:id' => 'jobs#show', :as => 'job'
get '/jobs/:id/edit' => 'jobs#edit', :as => 'edit_job'
put '/jobs/:id' => 'jobs#update', :as => 'update_job'
delete '/jobs/:id' => 'jobs#destroy', :as => 'destroy_job'

get "prompt/new" => 'prompt#new', :as => 'new_prompt'
post "prompt/create" => 'prompt#create'
delete "prompt/:id" => 'prompt#delete', :as => 'prompt'

get "/mockup/home" => 'mockup#home'


end

app/models/pitch.rb
class Pitch < ActiveRecord::Base
  attr_accessible :headline, :job_id, :user_id, :profilepic, :url_string, :avatar, :remove_avatar, :resume, :remove_resume, :video_link, :user_story, :background_image, :remove_background_image, :descriptive_url

  has_attached_file :profilepic
  
  belongs_to :job
  belongs_to :user
  has_many :prompts  
  has_many :pitch_attachments
  
  mount_uploader :avatar, AvatarUploader
  mount_uploader :resume, ResumeUploader
  mount_uploader :background_image, BackgroundImageUploader

  validates_presence_of :headline
  
  def url_string
    return "careerpivot.herokuapp.com/#{self.user.id}/#{self.id}/a-pitch-from/#{self.user.first_name}"
  end

  def short_url
    return "careerpivot.herokuapp.com/a_pitch/#{self.descriptive_url}"
  end

end

app/controllers/pitch_controller.rb
class  PitchController < ApplicationController

before_filter :ensure_logged_in, except: [:short_url]
before_filter :ensure_correct_user_id, only: [:show, :edit]


  def ensure_correct_user_id
    if session[:user_id] != Pitch.find_by_id(params[:id]).user_id
      flash[:message] = "You are not authorized to see/edit/delete any other User's user information."
      redirect_to user_url(session[:user_id])
    end
  end
  
  def destroy_pitch_attachments(id)
    pitch = Pitch.find_by_id(id)
    attachments = pitch.pitch_attachments
    attachments.destroy_all
  end

  def index
  	@pitches = Pitch.all
  end

  def show
  	@pitch = Pitch.find_by_id(params[:id])
    prompts = @pitch.prompts
    @prompts = Pitch.find_by_id(params[:id]).prompts
    @prompt_sample = @pitch.prompts.sample
    @pitch_attachments = @pitch.pitch_attachments
    @even_index_prompts = @prompts.values_at(* @prompts.each_index.select {|i| i.even?})
    @odd_index_prompts = @prompts.values_at(* @prompts.each_index.select {|i| i.odd?})
  end

  def new
  	@pitch = Pitch.new
    @job_id = params[:job_id]
    @prompt = Prompt.new
    @prompts = @pitch.prompts
    if @job_id == nil
      flash[:message] = "Current Pitch will not be linked to a job, the only way to have someone view it will be to send them the unique view link at the bottom of the Pitch."
    end
  end

  def create
  	@pitch = Pitch.new(params[:pitch])
  	@pitch.job_id = params[:job_id]
    @pitch.user_id = session[:user_id]
    if @pitch.save
      flash[:message] = "Pitch created and added to dashboard, now add prompts and attachments"
  	  redirect_to edit_pitch_url(@pitch.id)
    else 
      render 'new'
    end
  end

  def edit
  	@pitch = Pitch.find_by_id(params[:id])
    @prompt = Prompt.new
    @prompt_pitch_id = @pitch.id
    @prompts = @pitch.prompts
    @pitch_attachments = @pitch.pitch_attachments
  end

  def update
  	@pitch = Pitch.find_by_id(params[:id])
  	@pitch.update_attributes(params[:pitch])
  	redirect_to pitch_url(@pitch.id)
  end

  def destroy
  	@pitch = Pitch.find_by_id(params[:id])
    prompts = @pitch.prompts
    destroy_pitch_attachments(params[:id])
  	@pitch.destroy
    prompts.destroy_all
  	redirect_to user_url(session[:user_id])
  end
  
  def email
    #@email = Pitch.find_by_id(params[:id]).user.email
    @pitch = Pitch.find_by_id(params[:id])
    GeneralMailer.coffee_email(@pitch).deliver
    flash[:message] = "E-mail was sent!"
    redirect_to pitch_url(@pitch.id)
  end

  def short_url
    
    # @pitch = Pitch.where( :user_id => params[:userid], :id => params[:pitchid]).first
    @pitch = Pitch.where( descriptive_url: params[:short_descriptive_url]).first
    prompts = @pitch.prompts
    @prompts = prompts
    @prompt_sample = @prompts.sample
    @pitch_attachments = @pitch.pitch_attachments
    @even_index_prompts = prompts.values_at(* prompts.each_index.select {|i| i.even?})
    @odd_index_prompts = prompts.values_at(* prompts.each_index.select {|i| i.odd?})
    @marker = true

    render 'short_url_alternate'

  end


end

app/views/pitch/_form.html.erb
<!-- Pitch form_for Partial -->

<%= form_for(@pitch) do |f| %>
  <% if @pitch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pitch.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
      	<% @pitch.errors.full_messages.each do |msg| %>
        	<li><%= msg %></li>
      	<% end %>
      </ul>
    </div>
   <% end %>
<%end %>

<div class="row-fluid">
  <div class="span6 offset3 well">
    
<%= form_for @pitch, :html => {:class => "form-horizontal" } do |f| %>
  <fieldset>
	<%= f.label :headline, "Enter Headline"%>
	<%= f.text_field :headline, class: "span12" %></br>

  <%= f.label :descriptive_url, "Enter a descriptive url (it's how your target employer will find your pitch page" %>
  <%= f.text_field :descriptive_url %>


  <%= f.label :user_story, "Enter User Story" %>
  <%= f.text_area :user_story, size: "60x5"%></br>
	<!-- Must eventually be a collection select or auto-populate -->
	<% if params[:job_id].present? && session[:user_id].present? %>

		<%= hidden_field_tag :job_id, @job_id %>
	<% else %>
		<%#= f.label :job_id %>
		<%#= f.text_field :job_id %>

		<%#= f.label :user_id %>
		<%#= f.text_field :user_id %>
	<% end %>
	  

  <% if @pitch.avatar.present? %>
  	<%= f.label :remove_avatar, "Delete image" %>
  	<%= f.check_box :remove_avatar %>
  <% else %>
    <%= f.label :avatar, "Upload Avatar" %>
    <%= f.file_field :avatar%>
  <%end%>

	<% if @pitch.resume.present? %>
  	<%= f.label :remove_resume, "Delete resume" %>
  	<%= f.check_box :remove_resume, :class => "checkbox" %>
  <%else%>
    <%= f.label :resume %>
    <%= f.file_field :resume %>
  <%end%>

  <% if @pitch.background_image.present? %>
    <%= f.label :remove_background_image, "Delete background image" %>
    <%= f.check_box :remove_background_image, :class => "checkbox" %>
  <%else%>
    <%= f.label :background_image %>
    <%= f.file_field :background_image %>
    <p><small>Quick tip: images too dark or too bright might have text that doesn't read well </small></p>
  <%end%>

    <br><br>
    <%= f.label :video_link, "Put a Youtube embed string in" %>
    <%= f.text_field :video_link %>

  <%#end%> 




<% if @pitch.id %>
  <h3> Create custom questions</h3> 
  
  <ul class="talking_point_list">
    These could be...
    <li> Talking points to address concerns an employer might have </li>
    <li> Highlight your unique skills </li>
    <li> Things that make you awesome and special </li>
    <li> Things you're passionate about that tell us who you are </li> <br>
  </ul>

    <%= link_to "Create Custom Question", "/prompt/new?pitch_id=#{@pitch.id}", remote: true, id: "new_prompt_link" %>

  <h4> Manage existing custom questions: </h4>

    <ul id="existing_prompts">
    <% if @prompts.any? %>
      <% @prompts.each do |prompt_object| %>
        <li>
          <%= prompt_object.custom_question %><br>
          <%= prompt_object.custom_answer %><br>
          <%= link_to "Delete this question", prompt_url(prompt_object.id), method: 'delete' %>
        </li>
      <%end%>
    <%end%>

    </ul>

  <h4> Manage existing prompts: </h4>
   <%= link_to "Add Attachment", "/pitch_attachment/new?pitch_id=#{@pitch.id}", id: "new_attachment_link" %>

   <ul id="existing_attachments">
    <% if @pitch_attachments.any? %>
      <% @pitch_attachments.each do |pitch_attachment_object| %>
        <li>
          <b> Name: </b><%= pitch_attachment_object.name %><br>
          <% if pitch_attachment_object.attachment_url.end_with?('.pdf') ||   
            pitch_attachment_object.attachment_url.end_with?('.doc') ||
            pitch_attachment_object.attachment_url.end_with?('.pages') %>
      <%= link_to image_tag("document_image.jpeg"), pitch_attachment_object.attachment_url.to_s %><br>
      <%else%>
            <%= link_to image_tag(pitch_attachment_object.attachment_url), pitch_attachment_object.attachment_url.to_s%><br>
      <%end%>
          Click thubnail to Download<br>
          <!-- <b> Pitch Attachment ID: </b> --> <%#= pitch_attachment_object.id %>
          <!-- <b> Pitch ID: </b>  --><%#= pitch_attachment_object.pitch_id %>
          <%= link_to "Edit this attachment", pitch_attachment_edit_url(pitch_attachment_object.id) %><br>
          <%= link_to "Delete this attachment", pitch_attachment_destroy_url(pitch_attachment_object.id), method: 'delete' %><br>
        </li>
      <%end%>

    <%end%>

    </ul>





  	<br><br><br>
<% end %>
<%= f.submit "Submit",:class => "btn btn-primary"%>
</fieldset>
<%end%>

<small>* Denotes field that can't be blank </small>
</div>
</div>

app/views/pitch/edit.html.erb
<!--  Edit A Pitch -->

<h1>Tailor Your Pitch to a Specific Employer</h1>
<h1>Add an avatar, resume, background image, custom questions, video and attachments below</h1>

<%= render 'form' %>

app/views/pitch/index.html.erb
<!-- index.html.erb -->

<h1> Pitch Index </h1>
<ul>
<% @pitches.each do |pitch_object| %>
	<li>
		<b>Pitch Id: </b> <%= pitch_object.id %><br>
		<b>Pitch Headline: </b><%= pitch_object.headline %><br>
		<b>User ID: </b> <%= pitch_object.user_id %>
		<b>Job ID: </b> <%= pitch_object.job_id %>
<%= link_to 'Destroy', pitch_object, method: :delete, data: { confirm: 'Are you sure?' } %>
	</li>

<%end%>

app/views/pitch/new.html.erb
<!-- New Pitch Form -->

<h1>Get Started With a New Pitch</h1>
<h1>We'll let you customize your information on the next screen</h1>

<%= render 'form' %>

app/views/pitch/short_url.html.erb
<div class="container-fluid">
<!-- EMAIL AND PITCH TITLE PAGE -->
<p><b>Like what you see? </b> <%= link_to "Email", email_url(@pitch.id)%> this candidate</p>

<h2><%=@pitch.user.first_name.capitalize %>'s pitch</h2>

<div class="jumbotron center">
  
  <% if session[:user_id] && @pitch.job_id.nil? %>
        
    <h1><%= @pitch.headline%></h1>
    <hr>

  <div class="row-fluid span12 ">
    <%= image_tag @pitch.avatar_url(:thumb).to_s, :size=>'100x100', :class => "row-fluid span2"%>
    
    
    <p class="row-fluid span8"><b><%= @pitch.user.first_name.capitalize%>'s Story:</b> <%#= @pitch.user_story %>  User story will go here!</p>
  </div>

<div class="row-fluid span12">
  <% if @pitch.resume_url %>
    <p> <%= link_to "Download My Resume", @pitch.resume_url %> </p>
  <% end %>
</div>

        
  <%end%>

  <% if @pitch.video_link[/youtu\.be\/([^\?]*)/] %>
    <% youtube_id = $1%>
  <%else%>
    <%@pitch.video_link[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]%>
    <%youtube_id = $5%>
  <%end%>

    <div class="row-fluid span8 "><!-- offset3 marketing -->
      <iframe width="640px" height="390px"src= "http://www.youtube.com/embed/<%=youtube_id%>" frameborder="0" allowfullscreen ></iframe>
    </div>  
<!-- 
  </div> -->
 <div class="row-fluid span8">
    <div class="row-fluid span8 marketing">
      <div class="span4">
        <% @even_index_prompts.each do |prompt_object| %>
          <h4><%= prompt_object.custom_question %></h4>
          <p><%= prompt_object.custom_answer %></p>
        <%end%>
      </div>
      <div class="span4">
        <% @odd_index_prompts.each do |prompt_object| %>
          <h4><%= prompt_object.custom_question %></h4>
          <p><%= prompt_object.custom_answer %></p>
        <%end%>
      </div>
    </div>
  </div>


<div class="row-fluid marketing">
    <div class="row-fluid span12">  
    <% if @pitch_attachments.any? %>
     <h3> Attachments: </h3>
     <ul id="existing_attachments">
      <% @pitch_attachments.each do |pitch_attachment_object| %>
        <li class="row-fluid span3">
          <b> Name: </b><%= pitch_attachment_object.name %><br>
          <%= link_to image_tag(pitch_attachment_object.attachment_url), pitch_attachment_object.attachment_url.to_s%><br>
          Click thumbnail to Download<br>
          <!-- <b> Pitch Attachment ID: </b> --> <%#= pitch_attachment_object.id %>
          <!-- <b> Pitch ID: </b>  --><%#= pitch_attachment_object.pitch_id %>
          <%= link_to "Delete this attachment", pitch_attachment_destroy_url(pitch_attachment_object.id), method: 'delete' %>
        </li>
      <%end%>
    <%end%>
  </div>
</div>

      <hr>

app/views/pitch/short_url_alternate.html.erb
<!-- SPECIFIC PAGE STYLINGS -->
<style type="text/css">

/*Re-does body css if background image is present*/
<% if @pitch.background_image != nil && !@pitch.background_image.blank?%>
  body {
    background: white;
    background-image: url(<%= @pitch.background_image_url.to_s %>);
    background-size: cover;
    background-attachment: fixed;
    background-repeat: no-repeat;
    background-position:  absolute;
    }

    #like_what_you_see {
      color: white;
    }

    #users_pitch {
      color: white;
    }
<%else%> 
    body { background: white; }
<%end%>

.row-fluid{
  background: rgba(0, 0, 0, .55); /*opaque black*/
  margin-bottom: 2px;
  margin-top: 2px;
  margin-right: 200px;
  border-right: 200px;
  padding: 20px;
  border-radius: 5px;
  color: white;
}

.pagination-centered{
  text-align: left;
  margin-left: 200px;
  margin-right: 200px;
}

.row-fluid .span8 h4 {
  border-bottom: 1px solid black;
}

.row-fluid .span6 {
  margin-left: 20px;
}

.row-fluid .span6 h4{
  border-bottom: 1px solid black;
}

#fixed_pic {
    background-attachment: fixed;
    background-repeat: no-repeat;
    background-position:  absolute;
}
</style>


<div id="top"></div>
<!-- All blocks are in div span 8, all span classes per row should add to 8 -->

<!-- ABOVE BLOCKS - EMAIL PROMPT, "USER'S PROMPT" AND PITCH HEADLINE -->
<h4 id="like_what_you_see"><b>Like what you see? Email </b> <%= mail_to @pitch.user.email, @pitch.user.first_name %></h4>

<h2 id="users_pitch"><%=@pitch.user.first_name.capitalize %>'s pitch</h2>
      <p>
        <h1><%= @pitch.headline%></h1>
      </p>



<!-- This div makes all the row's span 8, it's very important -->
<div class="span8 pagination-centered ">

<!-- BLOCK 1 - AVATAR, RESUME AND USER STORY -->
<div class="row-fluid" >
  <div class="span2" id="fixed_pic" >
        <%= image_tag @pitch.avatar_url(:thumb).to_s, :size=>'100x100', :style => "border: 10px solid white;"%>
        <%= @pitch.user.twitter_handle %>
  </div>


  <div class="span6" >
        <h4><b><%= @pitch.user.first_name.capitalize%>'s Story</b></h4><p> <%= @pitch.user_story %> </p>
  </div>
</div>


<!-- BLOCK 2 - USER VIDEO -->
<div class="row-fluid">
  <div class="span8 offset2" >
      <% if @pitch.video_link[/youtu\.be\/([^\?]*)/] %>
        <% youtube_id = $1%>
      <%else%>
        <%@pitch.video_link[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]%>
        <%youtube_id = $5%>
      <%end%>
    <h4><b> Pitch Video</b> </h4>      
    <iframe width="407px" height="284px"src= "http://www.youtube.com/embed/<%=youtube_id%>" frameborder="0" allowfullscreen ></iframe>
  </div>
</div>
 

<!-- BLOCK 3 - USER PROMPTS, INTENDED TO BE TWO COLUMNS -->
<!-- <div class="row-fluid">
  <div class="span4 offset2">
      <%# @even_index_prompts.each do |prompt_object| %>
        <h4><%#= prompt_object.custom_question %></h4>
        <p><%#= prompt_object.custom_answer %></p>
      <%#end%>
  </div>
  <div class="span4" >        
      <%# @odd_index_prompts.each do |prompt_object| %>
        <h4><%#= prompt_object.custom_question %></h4>
        <p><%#= prompt_object.custom_answer %></p>
      <%#end%>
  </div>
</div> -->

<!-- BLOCK 3 - USER PROMPTS AS CAROUSEL -->
<!-- if no prompts: line break, if one prompt: display, if many prompts: carousel -->
<% if @prompts.count < 1 %>
<% elsif @prompts.count == 1 %>
  <div class="row-fluid">
    <div class="span8 offset2">
      <h4><%= @prompts.first.custom_question %></h4>
      <p> <%= @prompts.first.custom_answer %>  </p>
    </div>
  </div>
<% else %>
  <div class="row-fluid">
    <div class="span12">
      <div id="myCarousel" class="carousel slide">
        <!-- Carousel items -->
        <div class="carousel-inner">
          <div class="active item">
              <div class="span8 offset2">
              <h4><%= @prompt_sample.custom_question %></h4>
              <p><%=  @prompt_sample.custom_answer %></p>
              </div>
          </div>
          <% @prompts.each do |prompt_object| %>
              <div class="item">
                <div class="span8 offset2">
                <h4><%= prompt_object.custom_question %></h4>
                <p><%= prompt_object.custom_answer %></p>
                </div>
              </div>
          <%end%>
        </div>
        <!-- Carousel nav -->
    <a class="carousel-control left"  href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a> 
      </div>
    </div>
  </div>
<% end %>


<!-- BLOCK 4 - PITCH ATTACHMENTS -->
<% if @pitch_attachments.any? %>
  <% @pitch_attachments.each do |pitch_attachment_object| %>
    <div class="row-fluid">
     <div class="span8 offset2" >
            <%if pitch_attachment_object.name == "" || pitch_attachment_object.name == nil%>
            <h4 style="border-bottom: 1px solid black;">
            Attachment</h4>
          <%else%>
            <h4 style="border-bottom: 1px solid black;">
            Attachment - <%= pitch_attachment_object.name %></h4>
          <%end%>
          <% if pitch_attachment_object.description %>
            <small> <%= pitch_attachment_object.description %></small><br><br>
          <%end%>
      <% if pitch_attachment_object.attachment_url.end_with?('.pdf') ||   
            pitch_attachment_object.attachment_url.end_with?('.doc') ||
            pitch_attachment_object.attachment_url.end_with?('.pages') %>
      <%= link_to image_tag("document_image.jpeg"), pitch_attachment_object.attachment_url.to_s %><br>
      <%else%>
            <%= link_to image_tag(pitch_attachment_object.attachment_url), pitch_attachment_object.attachment_url.to_s%><br>
      <%end%>
            <small><small>Click thumbnail to Download</small></small><br>
     </div>
    </div>
  <%end%>
<%end%>

<!-- BLOCK 6 - BUT WAIT THERE'S MORE -->
<% if @pitch.resume_url %>
  <div class="row-fluid">
    <div class="span8 offset2">
      <h4><b>Wait, I still have more to offer </h4> 
      <p> <%= link_to "Download My Resume", @pitch.resume_url %> </p>
    </div>
  </div>
 <% end %>


<!-- BELOW BLOCKS - REPEAT OF USER'S EMAIL AND BACK TO TOP BUTTON, THEY HAVE INNER STYLING -->
<h4 id="like_what_you_see" style="float: left; padding-left: 20px; padding-bottom: 10px;"><b>Like what you see? Email </b> <%= mail_to @pitch.user.email, @pitch.user.first_name %></h4>
<h4><a href="#top" style="float: right; padding-bottom: 10px;"> Back to To Top </h4>


<!-- This closes out the master span 8 div on line approx line 26 -->
</div>


<script>
$('.carousel').carousel({
  interval: 500;
})
</script>