config/routes.rb
ThePitch::Application.routes.draw do

  get "pitch_attachment/new", :as => "new_pitch_attachment"
  post "pitch_attachment/create"

  delete '/pitch_attachment/:id' => 'PitchAttachment#destroy', :as => "pitch_attachment_destroy"

  get '/pitch_attachment/:id/edit' => 'PitchAttachment#edit', :as => "pitch_attachment_edit"

  put '/pitch_attachment/:id' => 'PitchAttachment#update', :as => "pitch_attachment_update"
 
  get "attachment/new"

  get "attachment/create"

  delete "attachment/delete"


root :to => 'Sessions#landingpage'

get '/aboutus' => 'sessions#about_us', :as => 'about_us'

get '/employerlogin' => 'sessions#newemployer', :as => 'employerlogin'
post '/sessions/createemployer' => 'sessions#create_employer'
get '/logout' => 'sessions#destroy', :as => 'logout'

get '/userlogin' => 'sessions#newuser', :as => 'userlogin'
post '/sessions/createuser' => 'sessions#create_user', :as => 'createuser'


get '/users', controller: 'Users', action: 'index', :as => 'users'
post '/users', controller: 'Users', action: 'create'
get '/users/new', controller: 'Users', action: 'new', :as => 'new_user'
get '/users/:id/edit', controller: 'Users', action: 'edit', :as => 'edit_user'
get '/users/:id', controller: 'Users', action: 'show', :as => 'user'

put '/users/:id', controller: 'Users', action: 'update'
delete '/users/:id', controller: 'Users', action: 'destroy'


get '/pitches/new' => 'Pitch#new', :as => 'new_pitch'
post '/pitches' => 'Pitch#create'
get '/pitches' => 'Pitch#index', :as => 'pitches'
get '/pitches/:id' => 'Pitch#show', :as => 'pitch'
delete '/pitches/:id' => 'Pitch#destroy'
put '/pitches/:id' => 'Pitch#update'
get '/pitches/:id/edit' => 'Pitch#edit', :as => 'edit_pitch'
post '/shorten/:id' => 'Pitch#shorten', :as => 'shorten'
get '/email/:id' => 'Pitch#email', :as => 'email'
get '/*userid/*pitchid/a-pitch-from/*userfirstname' => 'Pitch#short_url'
get '/a_pitch/*short_descriptive_url' => 'Pitch#short_url'

get '/employers' => 'employers#index', :as => 'employers'
get '/employers/new' => 'employers#new', :as => 'new_employer'
post '/employers' => 'employers#create'
get '/employers/:id' => 'employers#show', :as => 'employer'
get '/employers/:id/edit' => 'employers#edit', :as => 'edit'
put '/employers/:id' => 'employers#update', :as => 'update'
delete '/employers/:id' => 'employers#destroy', :as => 'delete'


get '/jobs' => 'jobs#index', :as => 'jobs'
get '/jobs/new' => 'jobs#new', :as => 'new_job'
post '/jobs' => 'jobs#create'
get '/jobs/:id' => 'jobs#show', :as => 'job'
get '/jobs/:id/edit' => 'jobs#edit', :as => 'edit_job'
put '/jobs/:id' => 'jobs#update', :as => 'update_job'
delete '/jobs/:id' => 'jobs#destroy', :as => 'destroy_job'

get "prompt/new" => 'prompt#new', :as => 'new_prompt'
post "prompt/create" => 'prompt#create'
delete "prompt/:id" => 'prompt#delete', :as => 'prompt'

get "/mockup/home" => 'mockup#home'


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :password, :password_confirmation, :linkedin_script, :password_digest, :twitter_handle
  
  has_secure_password
  
  validates_presence_of :email, :first_name, :last_name, :password, :password_confirmation
  validates_uniqueness_of :email

  has_many :pitches
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 before_filter :ensure_logged_in, except: [:new, :create]
 before_filter :ensure_correct_user_type
 before_filter :ensure_correct_user_id, only: [:show, :edit]

  def ensure_correct_user_type
    if session[:employer_id]
      flash[:message] = "Employers can not view any User pages"
      redirect_to employer_url(session[:employer_id])
    end
  end

  def ensure_correct_user_id
    if session[:user_id] != params[:id].to_i
      flash[:message] = "You are not authorized to see/edit/delete any other User's user information."
      redirect_to user_url(session[:user_id])
      return
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      GeneralMailer.user_signup_confirmation(@user).deliver
      flash[:message] = "Thanks for signing up, a confirmation e-mail has been sent to #{@user.email}."
      session[:user_id]=@user.id 
      redirect_to root_url
    else 
      flash[:message] = "Must fill out all required fields"
      render 'new'
    end
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.update_attributes(params[:user])
    redirect_to user_url
  end
 
  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    redirect_to users_url
  end
 


end

app/views/users/_form.html.erb
<div class="row-fluid">
  <div class="span5 well user_form">
    <%= form_for @user, :html => {:class => "form-horizontal"} do |f| %>
      <fieldset>
      	<%= f.label :first_name%>
        <%= f.text_field :first_name, :class => "span12"%>
          
      	<%= f.label :last_name%>
        <%= f.text_field :last_name, :class => "span12"%>

      	<%= f.label :email%>
        <%= f.text_field :email, :class => "span12", :html => {:status => :disabled }%>

        <!-- <%= f.label :linkedin_script%>
        <%= f.text_area :linkedin_script, :class => "span12", :size => '40x8' %> -->

        <%= f.label :password%>
        <%= f.password_field :password, :class => "span12"%>

       	<%= f.label :password_confirmation%>
        <%= f.password_field :password_confirmation, :class => "span12"%>

         <%= f.label :twitter_handle %>
         <%= f.text_field :twitter_handle, :class => "span12" %>

         <br><br>

        <%= f.submit "Submit",:class => "btn btn-primary"%>
        <%= link_to "Cancel", root_url, :class => "btn btn-primary", :style => "float: right;", :alert => "Really cancel?" %>
      </fieldset> 
    <% end %>
  </div>

  <div class="right_sidebar well span7"></div>
</div>

app/views/users/edit.html.erb
<h1>Edit <%= @user.first_name %>'s Information</h1>

<%= form_for(@user, :url => "/users/#{@user.id}") do |f| %>

	<%= f.label :first_name%>
  	<%= f.text_field :first_name%>
    
  	<%= f.label :last_name%>
    <%= f.text_field :last_name%>

 	<%= f.label :email%>
    <%= f.text_field :email%>

   	<%= f.submit %>
    <%= link_to "or Cancel", user_url(@user.id) %>

<% end%>

app/views/users/index.html.erb
<h1>User Index</h1>

<ul>
  <% @users.each do |user_object|%>
    <li>
      <%= user_object.first_name%>
      <%= user_object.last_name%>
      <%= user_object.email%>
      <%#= user_object.pitches%>
      <%#= user_object.jobs%>
      <%#= user_object.videos%>
      <%#= user_object.otherstuff%>
      <nav>
        <%= link_to "Delete", user_url(user_object.id), :method => 'delete', 'confirm' => "Are you sure?"%>
        <%= link_to "Edit", edit_user_url(user_object.id) %>
      </nav>
    </li>  
  <% end%>    
</ul>

app/views/users/new.html.erb
<h1>Ready to CareerPivot?</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row-fluid title">
    <div class="span4">
      <p><strong>Welcome, </strong>
        <%= @user.first_name.capitalize %>  
      </p>
    </div>
    <div class="span4">
      <p><strong>Email:</strong>
        <%= @user.email%>   
      </p>
    </div>
    <div class="span4">
      <p><strong><%= link_to "Edit User Information", edit_user_url(@user.id) %></strong></p>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span8 offset2">
        <div class="info">
         <th><h1>Existing Pitches</h1></th>
          <table class="table table-hover">
           
          <% @user.pitches.each do |pitch_object| %>
          <tr>
    		    <td><%= link_to pitch_object.headline, "/pitches/#{pitch_object.id}" %></td>
    			   <td><%= link_to "Edit", edit_pitch_url(pitch_object.id) %></td>
    			   <td><%= link_to "Delete", pitch_url(pitch_object.id), html_options = {method: 'delete', confirm: "Are you sure? Deleted Pitches can not be retrieved."} %></td>
          </tr>
          <%end%>
          
          </table>
        </div>
    </div>
  </div>
</div>