config/routes.rb
ThePitch::Application.routes.draw do

  get "pitch_attachment/new", :as => "new_pitch_attachment"
  post "pitch_attachment/create"

  delete '/pitch_attachment/:id' => 'PitchAttachment#destroy', :as => "pitch_attachment_destroy"

  get '/pitch_attachment/:id/edit' => 'PitchAttachment#edit', :as => "pitch_attachment_edit"

  put '/pitch_attachment/:id' => 'PitchAttachment#update', :as => "pitch_attachment_update"
 
  get "attachment/new"

  get "attachment/create"

  delete "attachment/delete"


root :to => 'Sessions#landingpage'

get '/aboutus' => 'sessions#about_us', :as => 'about_us'

get '/employerlogin' => 'sessions#newemployer', :as => 'employerlogin'
post '/sessions/createemployer' => 'sessions#create_employer'
get '/logout' => 'sessions#destroy', :as => 'logout'

get '/userlogin' => 'sessions#newuser', :as => 'userlogin'
post '/sessions/createuser' => 'sessions#create_user', :as => 'createuser'


get '/users', controller: 'Users', action: 'index', :as => 'users'
post '/users', controller: 'Users', action: 'create'
get '/users/new', controller: 'Users', action: 'new', :as => 'new_user'
get '/users/:id/edit', controller: 'Users', action: 'edit', :as => 'edit_user'
get '/users/:id', controller: 'Users', action: 'show', :as => 'user'

put '/users/:id', controller: 'Users', action: 'update'
delete '/users/:id', controller: 'Users', action: 'destroy'


get '/pitches/new' => 'Pitch#new', :as => 'new_pitch'
post '/pitches' => 'Pitch#create'
get '/pitches' => 'Pitch#index', :as => 'pitches'
get '/pitches/:id' => 'Pitch#show', :as => 'pitch'
delete '/pitches/:id' => 'Pitch#destroy'
put '/pitches/:id' => 'Pitch#update'
get '/pitches/:id/edit' => 'Pitch#edit', :as => 'edit_pitch'
post '/shorten/:id' => 'Pitch#shorten', :as => 'shorten'
get '/email/:id' => 'Pitch#email', :as => 'email'
get '/*userid/*pitchid/a-pitch-from/*userfirstname' => 'Pitch#short_url'
get '/a_pitch/*short_descriptive_url' => 'Pitch#short_url'

get '/employers' => 'employers#index', :as => 'employers'
get '/employers/new' => 'employers#new', :as => 'new_employer'
post '/employers' => 'employers#create'
get '/employers/:id' => 'employers#show', :as => 'employer'
get '/employers/:id/edit' => 'employers#edit', :as => 'edit'
put '/employers/:id' => 'employers#update', :as => 'update'
delete '/employers/:id' => 'employers#destroy', :as => 'delete'


get '/jobs' => 'jobs#index', :as => 'jobs'
get '/jobs/new' => 'jobs#new', :as => 'new_job'
post '/jobs' => 'jobs#create'
get '/jobs/:id' => 'jobs#show', :as => 'job'
get '/jobs/:id/edit' => 'jobs#edit', :as => 'edit_job'
put '/jobs/:id' => 'jobs#update', :as => 'update_job'
delete '/jobs/:id' => 'jobs#destroy', :as => 'destroy_job'

get "prompt/new" => 'prompt#new', :as => 'new_prompt'
post "prompt/create" => 'prompt#create'
delete "prompt/:id" => 'prompt#delete', :as => 'prompt'

get "/mockup/home" => 'mockup#home'


end

app/views/layouts/_header.html.erb
<div class="nav navbar">
  <div class="navbar-inner">      
    <ul class="nav pull-right">
      <% if !@marker %>
          <% if session[:user_id]==nil %>
          	<li class="divider-vertical"><%=link_to "CareerPivot", root_url %></li>
          	<li class="divider-vertical"><%= link_to "Sign Up Here!", new_user_url %></li>
     		<li class="divider-vertical"><%=link_to "About CareerPivot", about_us_url %></li>
     
          <% elsif User.find_by_id(session[:user_id])%>
          	<li class="divider-vertical"><%=link_to "About CareerPivot", about_us_url %></li>
          	<li class="divider-vertical"><%= link_to "Dashboard", user_url(session[:user_id]) %></li>
          	<li class="divider-vertical"><%= link_to "New Pitch", new_pitch_url %></li>
          	<li class="divider-vertical"><%= link_to "Logout", logout_url%></li>
          <%end%>
       
          <%else %>
          	<li class="divider-vertical"><%=link_to "CareerPivot Home", root_url %></li> 
          	<li class="divider-vertical"> <%= link_to "About CareerPivot", about_us_url%> </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title><%= content_for?(:title) ? yield(:title) : "CareerPivot" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  
  <body>

    <%= render "layouts/header" %>
    <%= yield %>


    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

   

  
  </body>

</html>